wartime_app/config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :students
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: 'home#index'

  get '/students/:id', to: 'home#students'

  resources :students do
    member do
      get :ping
    end
  end

  resources :todos, only: %i[index create destroy] do
    member do
      get :mark_as_done
    end
  end
end

wartime_app/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(student)
    return unless student
    if student.is_admin?
      can :manage, Student, :all
    else
      can :read, Student, faculty_id: student.faculty_id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

wartime_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

wartime_app/app/models/course.rb
class Course < ApplicationRecord
  has_and_belongs_to_many :students
end

wartime_app/app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :students
end

wartime_app/app/models/grade_book.rb
class GradeBook < ApplicationRecord
  belongs_to :student
end

wartime_app/app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true
  validates :first_name, length: { in: 2..100 }

  has_one :grade_book
  belongs_to :faculty
  has_and_belongs_to_many :courses

  before_save :do_something
  after_create do |record|
    puts "===created student #{record.full_name}==="
  end

  def full_name
    "#{first_name} #{last_name}".strip
  end

  def do_something
    puts 'Doing something...'
  end

  def avg_rating
    grade_book&.avg_rating
  end

  def is_admin?
    role == 'admin'
  end
end

wartime_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  private

  def set_locale
    ::I18n.locale = params[:locale] || 'en'
  end
end

wartime_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_student!, except: [:index]
  
  def index
    @students = ::Student.accessible_by(Ability.new(current_student))
  end

  def students
    student = ::Student.find params[:id]
    @name = student.full_name
  end
end

wartime_app/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def ping
    @student = ::Student.find params[:id]
    jid = ::PingWorker.perform_async(@student.id, 8)
    render plain: 'pinged...'
  end
end

wartime_app/app/helpers/application_helper.rb
module ApplicationHelper
end

wartime_app/app/views/home/index.html.erb
<h1><%= t('webui.students.index.title') %></h1>
<table class="table">
  <thead>
    <tr>
      <th><%= t('webui.students.index.name') %></th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.full_name %></td>
      <td><%= student.email %></td>
      <td class="actions">
        <% if Ability.new(current_student).can?(:update, Student) %>
          <%= link_to 'Edit', 'students/edit', {class: 'btn btn-info'} %>
          <%= link_to 'Ping', ping_student_path(student), {class: 'btn btn-warning'} %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

wartime_app/app/views/home/students.html.erb
<h1>Hello, <%= @name %></h1>
foo <b>bar</b>

wartime_app/app/views/layouts/_logged_in.html.erb
<% if student_signed_in? %>
  <div align="right">
    Logged in as <%= current_student.email %>
    <form action="<%= destroy_student_session_path %>" method="post">
      <input type="hidden" name="_method" value="delete">
      <input type="submit" value="Log out" class="btn btn-danger">
    </form>
  </div>
<% else %>
  <div align="right"><%= link_to 'Log in', new_student_session_path %></div>
<% end %>

wartime_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wartime App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= render partial: '/layouts/logged_in' %>
      <%= yield %>
    </div>
  </body>
</html>